config/routes.rb
Rails.application.routes.draw do
  resources :offices do
    get 'contact' => 'contact#new'
    post 'contact' => 'contact#create'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users do
    get 'contact' => 'contact#new'
    post 'contact' => 'contact#create'
  end

  resources :awardings

  resources :recipients do
    get :autocomplete_recipient_name, on: :collection
    get :armory, on: :collection
  end

  resources :awards do
    get :autocomplete_award_name, on: :collection
  end

  get '/pages' => 'pages#index'
  get '/pages/new' => 'pages#new', as: :new_page
  post '/pages' => 'pages#create'
  get '/*slug/edit' => 'pages#edit', as: :edit_page
  get '/*slug' => 'pages#show', as: :page
  patch '/*slug' => 'pages#update'
  put '/*slug' => 'pages#update'
  delete '/*slug' => 'pages#destroy'

  root 'pages#show', defaults: { slug: 'home' }

end

app/models/recipient.rb
# frozen_string_literal: true
class Recipient < ApplicationRecord
  include Heraldic

  has_many :awardings
  has_many :awards, through: :awardings
  has_one  :user

  def fix_empty(attr, value)
    value = nil if value && value.match(/^\s*$/)
    self[attr] = value
  end

  def sca_name=(value)
    fix_empty(:sca_name, value)
  end

  def mundane_name=(value)
    fix_empty(:mundane_name, value)
  end

  def formerly_known_as=(value)
    fix_empty(:formerly_known_as, value)
  end

  def also_known_as=(value)
    fix_empty(:also_known_as, value)
  end

  def heraldry_blazon=(value)
    fix_empty(:heraldry_blazon, value)
  end

  def title=(value)
    fix_empty(:title, value)
  end

  def pronouns=(value)
    fix_empty(:pronouns, value)
  end

  def to_s
    # if both SCA name and mundane name exist, return both. Otherwise, use
    # whichever is populated.

    if is_group
      "#{sca_name} (Group)"
    elsif both_names?
      "#{format_sca_name} #{format_inserts}(modernly known as #{mundane_name})"
    else
      format_one_name
    end
  end

  validates :sca_name, presence: true, if: :is_group
  validates :mundane_name, absence: true, if: :is_group

  validates :sca_name, presence: true, if: -> { mundane_name.blank? }
  validates :mundane_name, presence: true, if: -> { sca_name.blank? }

  private

  def both_names?
    sca_name && mundane_name && sca_name != '' && mundane_name != ''
  end

  def format_one_name
    display_name = if format_sca_name&.empty?
                     mundane_name
                   else
                     format_sca_name
                   end

    if format_inserts.empty?
      display_name
    else
      "#{display_name} #{format_inserts}"
    end
  end

  def format_sca_name
    if sca_name && title
      title + ' ' + sca_name
    elsif sca_name
      sca_name
    else
      ''
    end
  end

  def format_inserts
    display_inserts = ''

    if also_known_as && !also_known_as.empty?
      display_inserts += "(also known as #{also_known_as}) "
    end

    if formerly_known_as && !formerly_known_as.empty?
      display_inserts += "(formerly known as #{formerly_known_as}) "
    end

    display_inserts
  end
end

app/controllers/recipients_controller.rb
# frozen_string_literal: true
class RecipientsController < ApplicationController
  load_and_authorize_resource

  # override autocomplete from rails-autocomplete to search composite
  def autocomplete_recipient_name
    term = params[:term]

    items = if term && !term.blank?
              search_recipients(term)
            else
              {}
            end

    render json: json_for_autocomplete(items, :to_s)
  end

  def armory
    @armory_people = @recipients.where.not(heraldry_file_name: nil).order(:sca_name)
    render :armory
  end

  # GET /recipients
  # GET /recipients.json
  def index
    order = Arel.sql('coalesce(sca_name,mundane_name) ASC')
    @search = params[:search]
    @recipients = if @search
                    search_recipients(@search).order(order)
                  else
                    Recipient.order(order)
                  end
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)

    respond_to do |format|
      if @recipient.save
        format.html { redirect_to @recipient, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @recipient }
      else
        format.html { render :new }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        format.html { redirect_to @recipient, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url, notice: 'Recipient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipient_params
    params.require(:recipient).permit(:sca_name, :mundane_name, :is_group, :also_known_as, :formerly_known_as, :title, :pronouns, :heraldry, :heraldry_blazon, :mundane_bio, :sca_bio, :activities, :food_prefs)
  end

  def search_recipients(term)
    Recipient.where('mundane_name like :term or sca_name like :term or also_known_as like :term or formerly_known_as like :term', term: "%#{term}%")
  end
end

app/views/recipients/_awards.html.erb
<% if recipient.awards.any? %>

  <div class="collapsible">
    <h5>Awards</h5>

    <table>
      <tr>
        <th>Award Name</th>
        <th>Date Received</th>
      </tr>

      <% recipient.awardings.order(:received).each do |awarding| %>
        <tr>
          <td><%= link_to awarding, awarding.award %></td>
          <td class="date-cell"><%= awarding.received %></td>
          <% if can? :edit, awarding %>
            <td><%= link_to 'Edit', edit_awarding_path(awarding) %></td>
          <% end %>
          <% if can? :delete, awarding %>
            <td><%= link_to 'Delete', awarding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>

    </table>
  </div>
<% else %>
  <p><i>No awards</i>
<% end %>

app/views/recipients/_awards_collapse.html.erb
<% if recipient.awards.any? %>

  <div class="collapsible">
    <h5>Awards</h5>
    <%= render partial: 'awards_table', locals: {recipient: recipient} %>

  </div>
<% else %>
  <p><i>No awards</i>
<% end %>

app/views/recipients/_awards_table.html.erb
<table class="awards">
<tr>
  <th>Award Name</th>
  <th>Date Received</th>
</tr>

<% recipient.awardings.order(:received).each do |awarding| %>
  <tr>
    <td><%= link_to awarding, awarding.award %></td>
    <td class="date-cell"><%= awarding.received %></td>
    <td><%= link_to 'Details', awarding_path(awarding) %></td>
    <% if can? :edit, awarding %>
      <td><%= link_to 'Edit', edit_awarding_path(awarding) %></td>
    <% end %>
    <% if can? :delete, awarding %>
      <td><%= link_to 'Delete', awarding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>

</table>

app/views/recipients/_form.html.erb
<%= form_for(@recipient) do |f| %>

  <% if @recipient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipient.errors.count, "error") %> prohibited this recipient from being saved:</h2>

      <ul>
      <% @recipient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :sca_name, "SCA name" %><br>
    <%= f.text_field :sca_name %>
  </div>
  <div class="field">
    <%= f.label :pronouns, "Preferred Pronouns" %><br>
    <%= f.text_field :pronouns %>
  </div>
  <div class="field">
    <%= f.label :mundane_name %><br>
    <%= f.text_field :mundane_name %>
  </div>
  <div class="field">
    <%= f.label :also_known_as %><br>
    <%= f.text_field :also_known_as %>
  </div>
  <div class="field">
    <%= f.label :formerly_known_as %><br>
    <%= f.text_field :formerly_known_as %>
  </div>

  <% if @recipient and !@recipient.user %>
    <div class="field">
      <%= f.label :is_group, "Group?" %>
      <%= f.check_box :is_group %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :heraldry %>
    <%= f.file_field :heraldry %>
  </div>
  <div class="field">
    <%= f.label :heraldry_blazon %>
    <%= f.text_field :heraldry_blazon %>
  </div>
  <div class="field">
    <%= f.label "SCA Biography" %>
    <%= f.text_area :sca_bio %>
  </div>
  <div class="field">
    <%= f.label "Mundane Biography" %>
    <%= f.text_area :mundane_bio %>
  </div>
  <div class="field">
    <%= f.label "Activities and Interests" %>
    <%= f.text_area :activities %>
  </div>
  <div class="field">
    <%= f.label "Food Preferences (Likes, Dislikes, Allergies)" %>
    <%= f.text_area :food_prefs %>
  </div>
  <div class="actions">
    <%= f.submit "#{action_name == 'new' ? 'Create' : 'Update'} Profile" %>
  </div>
<% end %>

app/views/recipients/armory.html.erb
<div class="armory-grid">
<% @armory_people.each do |r| %>
  <div class="armory-cell">
    <div class="armory-scaname"><%= link_to r.sca_name, r %></div>
    <%= render partial: 'heraldry', locals: {heraldic_object: r} %>
    <div class="armory-blazon"><%= r.heraldry_blazon %></div>
  </div>
<% end %>

</div>

app/views/recipients/edit.html.erb
<h3>Editing profile</h3>
<%= render 'form' %>

app/views/recipients/index.html.erb
<h1>Order of Precedence (By Name)</h1>

<%= render 'application/update_oop' %>

<p>
Search by name: 
<%= form_tag("",method:"get") do %>
  <%= text_field_tag 'search', @search %> 
  <%= submit_tag 'Search' %>
<% end %>
</p>

<% if @search and @recipients %>
  <p><a href="javascript:expandAll()">Expand All</a> | <a href="javascript:collapseAll()">Collapse All</a></p>
<% end %>

<% @recipients.each do |recipient| %>
  <h4><%= link_to recipient, recipient %></h4>
  <% if can? :edit, recipient %>
    <%= link_to 'Edit', edit_recipient_path(recipient) %>
  <% end %>
  <% if can? :delete, recipient %>
    <%= link_to 'Destroy', recipient, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

  <!-- only show dropdown if seraching -->
  <% if @search %>
    <%= render partial: 'awards_collapse', locals: {recipient: recipient} %>
  <% end %>
<% end %>

<br>

<% if can? :create, Recipient %>
  <%= link_to 'New Recipient', new_recipient_path %>
<% end %>

app/views/recipients/new.html.erb
<h3>New award recipient</h3>

<%= render 'form' %>

app/views/recipients/show.html.erb
<%= render partial: 'heraldry', locals: {heraldic_object: @recipient} %>

<h3><%= @recipient %></h3>

<% if @recipient.pronouns.present? %>
  <p><b>Preferred Pronouns:</b> <%= @recipient.pronouns %></p>
<% end %>

<% if @recipient.heraldry_blazon.present? %>
  <p><i><%= @recipient.heraldry_blazon %></i></p>
<% end %>

<% if @recipient.mundane_bio.present? || @recipient.sca_bio.present? %>
  <h4>Biography</h4>
<% end %>

<% if @recipient.sca_bio.present? %>
  <p><%= @recipient.sca_bio %></p>
<% end %>

<% if @recipient.mundane_bio.present? %>
  <p><%= @recipient.mundane_bio %></p>
<% end %>

<% if @recipient.activities.present? %>
  <h4>Activities and Interests</h4>
  <p><%= @recipient.activities %></p>
<% end %>

<% if @recipient.food_prefs.present? %>
  <h4>Food Preferences</h4>
  <p><%= @recipient.food_prefs %></p>
<% end %>

<%= render partial: 'awards_table', locals: {recipient: @recipient} %>

<% if can? :create, Awarding  %>
  <%= link_to 'Add Award', new_awarding_path(recipient_id: @recipient) %> | 
<% end %>
<% if can? :edit, @recipient %>
  <%= link_to 'Edit', edit_recipient_path(@recipient) %>
<% end %>

<p><%= render 'application/update_oop' %></p>

<p><%= link_to 'Show All Persons/Groups', recipients_path %>