config/routes.rb
Rails.application.routes.draw do
  resources :offices do
    get 'contact' => 'contact#new'
    post 'contact' => 'contact#create'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users do
    get 'contact' => 'contact#new'
    post 'contact' => 'contact#create'
  end

  resources :awardings

  resources :recipients do
    get :autocomplete_recipient_name, on: :collection
    get :armory, on: :collection
  end

  resources :awards do
    get :autocomplete_award_name, on: :collection
  end

  get '/pages' => 'pages#index'
  get '/pages/new' => 'pages#new', as: :new_page
  post '/pages' => 'pages#create'
  get '/*slug/edit' => 'pages#edit', as: :edit_page
  get '/*slug' => 'pages#show', as: :page
  patch '/*slug' => 'pages#update'
  put '/*slug' => 'pages#update'
  delete '/*slug' => 'pages#destroy'

  root 'pages#show', defaults: { slug: 'home' }

end

app/models/award.rb
# frozen_string_literal: true
class Award < ApplicationRecord
  include Heraldic

  has_many :awardings
  has_many :recipients, through: :awardings
  belongs_to :group

  validates :name, presence: true

  validates :description, presence: true,
                          length: { minimum: 30 }

  validates :precedence, presence: true

  has_many :awards, through: :awardings

  def to_s
    name
  end
end

app/controllers/awards_controller.rb
# frozen_string_literal: true
class AwardsController < ApplicationController
  load_and_authorize_resource

  autocomplete :award, :name, full: true

  # GET /awards
  # GET /awards.json
  def index
    if params[:search]
      @search = params[:search]
      @awards = Award.where('name like :search or description like :search', search: "%#{@search}%").order('name ASC')
    else
      @awards = Award.order('name ASC')
    end
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
  end

  # GET /awards/new
  def new
    @award = Award.new
  end

  # GET /awards/1/edit
  def edit
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(award_params)

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @award }
      else
        format.html { render :new }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      else
        format.html { render :edit }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award.destroy
    respond_to do |format|
      format.html { redirect_to awards_url, notice: 'Award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def award_params
    params.require(:award).permit(:name, :description, :precedence, :heraldry, :heraldry_blazon)
  end
end

app/views/awards/_details.erb
<% if award.heraldry_blazon %>
  <p> <i><%= award.heraldry_blazon %></i></p>
<% end %>

<p> <i><%= award.description %></i> </p>

<% if award.society %>
  <p> <i>Society-level award; can be awarded by any kingdom</i> </p>
<% end %>

<% if award.group and !award.society %>
  <p> <i>Awarded by the <%= award.group %></i></p>
<% end %>

app/views/awards/_form.html.erb
<%= form_for(@award) do |f| %>
  <% if @award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% @award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :precedence %><br>
    <%= f.number_field :precedence %>
  </div>
  <div class="field">
    <%= f.label :heraldry %>
    <%= f.file_field :heraldry %>
  </div>
  <div class="field">
    <%= f.label :heraldry_blazon %>
    <%= f.text_field :heraldry_blazon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/_recipients.html.erb
<% if award.recipients.any? %>

    <div class="collapsible">
        <h5>Recipients</h5>
        <table>
            <tr>
                <th>Name</th>
                <th>Date Received</th>
            </tr>
            <% award.awardings.order(:received).each do |awarding| %>
                <tr>
                    <td><%= link_to awarding.recipient, awarding.recipient %></td>
                    <td class="date-cell"><%= awarding.received %></td>
                    
                    <% if can? :edit, awarding %>
                      <td><%= link_to 'Edit', edit_awarding_path(awarding) %></td>
                    <% end %>

                    <% if can? :delete, awarding %>
                      <td><%= link_to 'Delete', awarding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <% end %>
                </tr>
            <% end %>

        </table>
    </div>
<% else %>
    <p><i>No recipients</i></p>
<% end %>

app/views/awards/_recipients_collapse.html.erb
<% if award.recipients.any? %>

    <div class="collapsible">
        <h5>Recipients</h5>
        <%= render partial: 'recipients_table', locals: {award: award} %>
    </div>
<% else %>
    <p><i>No recipients</i></p>
<% end %>

app/views/awards/_recipients_table.html.erb
<table class="awards">
<tr>
  <th>Name</th>
  <th>Date Received</th>
</tr>
<% award.awardings.order(:received).each do |awarding| %>
  <tr>
    <td><%= link_to awarding.recipient, awarding.recipient %></td>
    <td class="date-cell"><%= awarding.received %></td>

    <td><%= link_to 'Details', awarding_path(awarding) %></td>

    <% if can? :edit, awarding %>
      <td><%= link_to 'Edit', edit_awarding_path(awarding) %></td>
    <% end %>

    <% if can? :delete, awarding %>
      <td><%= link_to 'Delete', awarding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>

</table>

app/views/awards/edit.html.erb
<h1>Editing award type</h1>

<%= render 'form' %>

app/views/awards/index.html.erb
<h1>Order of Precedence (By Award)</h1>

<%= render 'application/update_oop' %>

<p>
Search award name and description: 
<%= form_tag("",method:"get") do %>
  <%= text_field_tag 'search', @search %> 
  <%= submit_tag 'Search' %>
<% end %>
</p>

<% if @search and @awards %>
  <p><a href="javascript:expandAll()">Expand All</a> | <a href="javascript:collapseAll()">Collapse All</a></p>
<% end %>

<% @awards.each do |award| %>
  <%= render partial: 'heraldry', locals: {heraldic_object: award} %>

  <h4><%= link_to award.name, award %></h4>

  <%= render partial: 'details', locals: {award: award} %>

  <% if can? :update, award %>
    <%= link_to 'Edit', edit_award_path(award) %>
  <% end %>
  <% if can? :delete, award %>
    <%= link_to 'Destroy', award, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

  <!-- only show dropdown if searching -->
  <% if @search %>
    <%= render partial: 'recipients_collapse', locals: {award: award} %>
  <% end %>

<% end %>

<br>

<% if can? :create, Award %>
  <%= link_to 'New Award', new_award_path %>
<% end %>

app/views/awards/new.html.erb
<h3>New award type</h3>

<%= render 'form' %>

app/views/awards/show.html.erb
<%= render partial: 'heraldry', locals: {heraldic_object: @award} %>

<h3><%= @award %></h3>
<%= render partial: 'details', locals: {award: @award} %>


<%= render partial: 'recipients_table', locals: {award: @award} %>


<% if can? :create, Awarding %>
  <%= link_to 'Add Recipient', new_awarding_path(award_id: @award) %> | 
<% end %>
<% if can? :edit, @award %>
  <%= link_to 'Edit', edit_award_path(@award) %> |
<% end %>

<p><%= render 'application/update_oop' %></p>

<p><%= link_to 'Show All Awards', awards_path %></p>