config/routes.rb
Rails.application.routes.draw do
  resources :offices do
    get 'contact' => 'contact#new'
    post 'contact' => 'contact#create'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users do
    get 'contact' => 'contact#new'
    post 'contact' => 'contact#create'
  end

  resources :awardings

  resources :recipients do
    get :autocomplete_recipient_name, on: :collection
    get :armory, on: :collection
  end

  resources :awards do
    get :autocomplete_award_name, on: :collection
  end

  get '/pages' => 'pages#index'
  get '/pages/new' => 'pages#new', as: :new_page
  post '/pages' => 'pages#create'
  get '/*slug/edit' => 'pages#edit', as: :edit_page
  get '/*slug' => 'pages#show', as: :page
  patch '/*slug' => 'pages#update'
  put '/*slug' => 'pages#update'
  delete '/*slug' => 'pages#destroy'

  root 'pages#show', defaults: { slug: 'home' }

end

app/models/awarding.rb
# frozen_string_literal: true
class Awarding < ApplicationRecord
  belongs_to :award
  belongs_to :recipient
  belongs_to :group

  validates :award, presence: true
  validates :recipient, presence: true

  # group should be present if there is no default group
  validates :group, presence: true, if: proc { |a| a.award.nil? || a.award.group.nil? }

  # award name override should be present iff the award is an 'other award'
  validates :award_name, presence: true, if: proc { |a| a.award.nil? || a.award.other_award? }
  validates :award_name, absence: true, if: proc { |a| a.award && !a.award.other_award? }

  # returns overriden value if present, otherwise falls back to award
  def override_attr(attr, own_attr_val)
    return own_attr_val if own_attr_val
    award.send(attr) if award
  end

  # returns override award name if one exists, otherwise the default group
  def group
    override_attr(:group, super)
  end

  # returns award name or display name (if other award) along with granting group (if not the default)
  def display_name
    override_attr(:name, award_name) + (group == award.group ? '' : " (#{group})")
  end

  def to_s
    display_name
  end

  def received
    return super if super
    '(Unknown)'
  end
end

app/controllers/awardings_controller.rb
# frozen_string_literal: true
# Controller for Awardings - instances of awards given to recipients
class AwardingsController < ApplicationController
  load_and_authorize_resource

  # GET /awardings
  def index
    begin
      @start_date = params[:start_date] ? Date.parse(params[:start_date]) : nil
      @end_date = params[:end_date] ? Date.parse(params[:end_date]) : nil
    rescue ArgumentError
      flash[:error] = 'Invalid date format - use date picker or specify YYYY-MM-DD'
    end

    filter_by_date
  end

  # GET /awardings/1
  def show
  end

  # GET /awardings/new
  def new
    @awarding = Awarding.new(params.permit(:award_id, :recipient_id))
  end

  # GET /awardings/1/edit
  def edit
  end

  # POST /awardings
  def create
    @awarding = Awarding.new(awarding_params)

    if @awarding.save
      redirect_to @awarding, notice: 'Awarding was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /awardings/1
  def update
    if @awarding.update(awarding_params)
      redirect_to @awarding, notice: 'Awarding was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /awardings/1
  def destroy
    @awarding.destroy
    redirect_to awardings_url, notice: 'Awarding was successfully destroyed.'
  end

  private

  def nil_award_name
    if params[:other_award] == '1'
      params[:awarding][:award_name] = nil if params[:awarding][:award_name].blank?
    else
      params[:awarding][:award_name] = nil
      params[:awarding][:group_id] = nil
    end
  end

  def nil_unknown_date
    if params[:awarding][:received]&.match(/unknown/i)
      params[:awarding][:received] = nil
    end
  end

  def awarding_params
    nil_award_name
    nil_unknown_date

    params.require(:awarding).permit(:award_id, :recipient_id, :received, :award_name, :group_id, :award_text)
  end

  def filter_by_date
    if @start_date && @end_date
      @awardings = Awarding.where('received >= ? and received <= ?', @start_date, @end_date).order(:received)
    else
      if @start_date || @end_date
        flash[:error] = 'To filter by date, both start date and end date must be provided'
      end
      @awardings = Awarding.order(:received)
    end
  end
end

app/views/awardings/_form.html.erb
<%= form_for(@awarding) do |f| %>
  <% if @awarding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@awarding.errors.count, "error") %> prohibited this awarding from being saved:</h2>

      <ul>
        <% @awarding.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <table class="awards">
    <tr>
      <th style="vertical-align: top">
        <%= f.label :recipient %>:
      </th>
      <td>
        <%= f.hidden_field :recipient_id %>
        <%= autocomplete_field_tag 'recipient_name', 
          @awarding.recipient ? @awarding.recipient.to_s : nil, 
          autocomplete_recipient_name_recipients_path, 
          :id_element => '#awarding_recipient_id',
          :"data-autocomplete-label" => "No matches",
          :size => 75 %> <br />
        <%= link_to 'Create new recipient', new_recipient_path %>
    </td>
    </tr>

    <tr>
      <th>
        <%= f.label :award_id %>:
      </th>
      <td>
        <%= f.hidden_field :award_id %>
        <%= autocomplete_field_tag 'award_name', 
          @awarding.award ? @awarding.award.name : nil, 
          autocomplete_award_name_awards_path, 
          :id_element => '#awarding_award_id',
          :size => 75 %>
    </td>
    </tr>

    <tr>
      <th>    <%= f.label :received %>: </th>
      <td>    <%= f.text_field 'received', class: 'datepicker' %></td>
    </tr>

    <tr>
      <th>  <%= f.label :award_text %>: </th>
      <td>  <%= f.text_area 'award_text' %> </td>
    <tr>
      <td>  Is other/foreign award? </td>
      <td>  <%= check_box_tag 'other_award', '1', (@awarding.award ? @awarding.award.other_award? : false) %> </td>

    <tr>
      <td>  <%= f.label :award_name %> (for foreign &amp; 'other' awards only) </td>
      <td>  <%= f.text_field 'award_name' %></td>
    </tr>

    <tr>
      <td>  <%= f.label :group_id %> (for foreign awards only, including AoAs, GoAs, and peerages): </td>
      <td>  <%= f.collection_select(:group_id, Group.all, :id, :name) %> </td>
    </tr>

  </table>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/awardings/edit.html.erb
<h3>Editing award receipt</h3>
<%= render 'form' %>

app/views/awardings/index.html.erb
<%= render 'application/update_oop' %>
 
<h4>Filter by Date:</h4>

<%= form_tag("",method:"get") do %>
  <p>Start: <%= text_field_tag 'start_date', @start_date, class: 'datepicker' %></p>
  <p>End: <%= text_field_tag 'end_date', @end_date, class: 'datepicker' %></p>
  <%= submit_tag 'Filter' %>
<% end %>


<% if @start_date and @end_date %>
  <h3>Showing awards received between <%= @start_date %> and <%= @end_date %></h3>
<%= form_tag("",method:"get") do %>
  <%= submit_tag 'Show All' %>
<% end %>
<% end %>

<% if @awardings.any? %>
<table class="awards">
  <thead>
    <tr>
      <th style="text-align: left; padding: 5px">Recipient/Award</th>
      <th style="text-align: left; padding: 5px">Received</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @awardings.each do |awarding| %>
      <tr>
        <td><%= link_to awarding.recipient, awarding.recipient %> 
        <br />
        <%= link_to awarding.award, awarding.award %></td>
        <td style="white-space: nowrap"><%= awarding.received %></td>
        <% if can? :edit, awarding %>
          <td><%= link_to 'Edit', edit_awarding_path(awarding) %></td>
        <% end %>
        <% if can? :delete, awarding %>
          <td><%= link_to 'Delete', awarding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h3><i>No awards found.</i></h3>
<% end %>

<br>

<% if can? :create, Awarding %>
  <%= link_to 'New Awarding', new_awarding_path %>
<% end %>

app/views/awardings/new.html.erb
<h3>New award receipt</h3>
<%= render 'form' %>

app/views/awardings/show.html.erb
<h3>
  <%= link_to @awarding, award_path(@awarding.award) %>
</h3>

<h4>
  Awarded to
  <%= link_to @awarding.recipient, recipient_path(@awarding.recipient) %>
</h4>

<h4>
  By the <%= @awarding.group %> on <%= @awarding.received %>
</h4>

<% if @awarding.award_text %>
  <p> <%= simple_format(@awarding.award_text) %> </p>
<% end %>


<% if can? :edit, @awarding %>
  <p><%= link_to 'Edit', edit_awarding_path(@awarding) %></p>
<% end %>
<% if can? :create, Awarding %>
  <p><%= link_to 'Add Award Receipt', new_awarding_path %></p>
<% end %>

<p><%= render 'application/update_oop' %></p>