config/routes.rb
Rails.application.routes.draw do
  resources :offices do
    get 'contact' => 'contact#new'
    post 'contact' => 'contact#create'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users do
    get 'contact' => 'contact#new'
    post 'contact' => 'contact#create'
  end

  resources :awardings

  resources :recipients do
    get :autocomplete_recipient_name, on: :collection
    get :armory, on: :collection
  end

  resources :awards do
    get :autocomplete_award_name, on: :collection
  end

  get '/pages' => 'pages#index'
  get '/pages/new' => 'pages#new', as: :new_page
  post '/pages' => 'pages#create'
  get '/*slug/edit' => 'pages#edit', as: :edit_page
  get '/*slug' => 'pages#show', as: :page
  patch '/*slug' => 'pages#update'
  put '/*slug' => 'pages#update'
  delete '/*slug' => 'pages#destroy'

  root 'pages#show', defaults: { slug: 'home' }

end

app/views/layouts/_grandday_menu.html.erb
<!-- Grand Day of Tournaments Menu  -->
  <li ><a href="/grandday">Event Home</a></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Event Info<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="/grandday/site">Site Information</a></li>
      <li><a href="/grandday/fees">Fees and Registration</a></li>
      <li><a href="/grandday/maps">Maps and Directions</a></li>
      <li><a href="/grandday/lodging">Lodging</a></li>
      <li><a href="/grandday/tavern">Tavern Menu</a></li>
      <li><a href="/grandday/staff">Event Staff</a></li>
    </ul>
  </li>
  <li ><a href="/grandday/schedule">Schedule</a></li>
  <li ><a href="/grandday/tournaments">Tournaments</a></li>
  <li ><a href="/grandday/merchants_populace">Merchants/Populace Activities</a></li>

app/views/layouts/_menu.html.erb
  <li ><a href="/events">Events & Demos</a></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Cynnabar<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <!--    <li><a href="/calendar">Calendar</a></li> -->
      <li><a href="/barons">Barons</a></li>
      <li><a href="/workshops">Workshops</a></li>
      <li><a href="/baronial-awards">Baronial Awards</a></li>
      <li><a href="/cynnabar-oop">Order of Precedence</a></li>
      <li><a href="/citadel">Newsletter</a></li>
      <li><a href="/history">History</a></li>
    </ul>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >For Newcomers<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="/chatelaine">Newcomer Info</a></li>
      <li><a href="/goldkey">Loaner Garb (Gold Key)</a></li>
      <li><a href="/sca_2004">What is the SCA?</a></li>
    </ul>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Martial Arts<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="/martial-arts">Calendar</a></li>
      <li><a href="/marshal">Armored Combat</a></li>
      <li><a href="/fencing-marshal">Rapier Combat</a></li>
      <li><a href="/archery">Archery</a></li>
    </ul>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Arts & Sciences<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="/moas">Calendar</a></li>
      <li><a href="/garb">Garb Workdays</a></li>
      <li><a href="/eurodance">European Dance</a></li>
    </ul>
  </li>
  <li class="dropdown officer-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Officers<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to "All Officers", offices_path %>
      <% Office.all.each do |office| %>
        <% if office.page %>
          <li >
            <%= link_to page_path(office.page) do %>
            <%= image_tag(office.image, :class => "officer-menu-image pull-left") %>
            <%= office.page.title %>
            <% end %>

          </li>
        <% end %>
      <% end %>
    </ul>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >The Known World<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="/neighbors">Neighbors</a></li>
      <li><a href="http://www.midrealm.org/pentamere/">Pentamere</a></li>
      <li><a href="http://www.midrealm.org">Midrealm</a></li>
      <li><a href="http://www.sca.org">The SCA</a></li>
      <li><a href="http://www.midrealm.org/calendar">Kingdom Calendar</a></li>
      <li><a href="https://a12c.enciva.com/apex/f?p=331:18">Kingdom Order of Precedence</a></li>
    </ul>
  </li>
  <li ><a href="/online-resources">Resources</a></li>

app/views/layouts/_submenu.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >User<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Change Password', edit_user_registration_path %>
    <% if current_user.recipient and can? :edit, current_user.recipient %>
      <li><%= link_to('Edit Profile', edit_recipient_path(current_user.recipient)) %></li>
    <% end %>
    <% if can? :list, User %>
      <li><%= link_to 'List Users', users_path %></li>
    <% end %>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
  </ul>
</li>

<% if (@page and can? :edit, @page) or can? :list, Page or can? :create, Page %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Page<span class="caret"></span></a>
    <ul class="dropdown-menu admin-links">
      <% if can? :create, Page %>
        <li class="page-new" data-no-turbolink><%= link_to 'New', new_page_path %></li>
      <% end %>
      <% if (@page and @page.slug and can? :edit, @page) %>
        <li class="page-edit" data-no-turbolink><%= link_to 'Edit', edit_page_path(@page) %></li>
      <% end %>
      <% if can? :index, Page %>
        <li class="page-index"><%= link_to 'List Pages', pages_path %></li>
      <% end %>
    </ul>
  </li>
<% end %>

<% if can? :manage, Awarding %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Precedence<span class="caret"></span></a>
    <ul class="dropdown-menu admin-links">
      <li><%= link_to 'Add Award Receipt', new_awarding_path %></li>
      <li><%= link_to 'All Award Receipts By Date', awardings_path %></li>
      <li><%= link_to 'OOP (By Name)', recipients_path %></li>
      <li><%= link_to 'OOP (By Award) ', awards_path %></li>
      <% if can? :create, Award %>
        <li><%= link_to 'New Award Type', new_award_path %></li>
      <% end %>
    </ul>
  </li>
<% end %>

app/views/layouts/_terpsichore_menu.html.erb
<!-- Terpsichore menu -->
  <li ><a href="/terpsichore">Event Home</a></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Event Info<span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><a href="/terpsichore/site">Site Information</a></li>
      <li><a href="/terpsichore/fees">Fees and Registration</a></li>
      <li><a href="/terpsichore/maps">Maps and Directions</a></li>
      <li><a href="/terpsichore/lodging">Lodging</a></li>
      <li><a href="/terpsichore/tavern">Tavern Menu</a></li>
      <li><a href="/terpsichore/staff">Event Staff</a></li>
    </ul>
  </li>
  <li ><a href="/terpsichore/schedule">Schedule</a></li>
  <li ><a href="/terpsichore/classes">Classes</a></li>
  <li ><a href="/terpsichore/ball">Grand Ball</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :title %></title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  </head>
  <body class="main-body">
    <nav class="navbar navbar-default hidden-lg hidden-md mobile-nav">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-items">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/"><span class="navbar-brand navbar-brand-img"><%= image_tag("cynnabar_arms.svg", :class=>'brand-img') %></span>
            <span class="navbar-toggle collapsed navbar-brand pull-left">Barony of Cynnabar</span></a>
        </div>
        <div class="collapse navbar-collapse" id="menu-items">
          <ul class="nav navbar-nav">
            <%= render menu %>
            <% if user_signed_in? %>
              <%= render 'layouts/submenu' %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container wrapper">
      <div class="row">
        <div class="col-md-12 main-box">
          <div id="header-region" class="center-block hidden-sm hidden-xs">
            <a href="/"><img src="<%= logo %>" /></a>
          </div>
          <nav class="navbar navbar-default hidden-sm hidden-xs" id="menu-region">
            <div class="container">
              <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                  <%= render menu %>
                </ul>
              </div>
            </div>
          </nav>

          <% if user_signed_in? %>
            <nav class="navbar navbar-default hidden-sm hidden-xs" id="submenu-region">
              <div class="container">
                <div class="collapse navbar-collapse">
                  <ul class="nav navbar-nav">
                    <%= render 'layouts/submenu' %>
                  </ul>
                </div>
              </div>
            </nav>
          <% end %>

          <div id="main-region">
            <div class="flash">
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>